apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: integration
  labels:
    app: integration
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      namespace: default
      labels:
        app: integration
    spec:
      containers:
        - name: integration
          image: osones/helloworld:v1
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: integration-svc
spec:
  ports:
  - name: admin
    port: 8000
    targetPort: 80
    protocol: TCP
  selector:
    app: integration
  type: LoadBalancer
