---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: 16.04
inputs:
  - name: gh-torrent
  - name: gh-release-torrent
outputs:
  - name: output
run:
  path: gh-torrent/.ci/make.sh
